/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.joaogsma

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testExample1InputVersion1() {
        assertEquals(7, runProblem1("example1.txt"))
    }

    @Test fun testExample2InputVersion1() {
        assertEquals(5, runProblem1("example2.txt"))
    }

    @Test fun testExample3InputVersion1() {
        assertEquals(6, runProblem1("example3.txt"))
    }

    @Test fun testExample4InputVersion1() {
        assertEquals(10, runProblem1("example4.txt"))
    }

    @Test fun testExample5InputVersion1() {
        assertEquals(11, runProblem1("example5.txt"))
    }

    @Test fun testRealInputVersion1() {
        assertEquals(1766, runProblem1("input.txt"))
    }

    @Test fun testExample1InputVersion2() {
        assertEquals(19, runProblem2("example1.txt"))
    }

    @Test fun testExample2InputVersion2() {
        assertEquals(23, runProblem2("example2.txt"))
    }

    @Test fun testExample3InputVersion2() {
        assertEquals(23, runProblem2("example3.txt"))
    }

    @Test fun testExample4InputVersion2() {
        assertEquals(29, runProblem2("example4.txt"))
    }

    @Test fun testExample5InputVersion2() {
        assertEquals(26, runProblem2("example5.txt"))
    }

    @Test fun testRealInputVersion2() {
        assertEquals(2383, runProblem2("input.txt"))
    }
}
