/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.joaogsma

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testExample() {
        assertEquals(12, run("example.txt"))
    }

    @Test fun testInput() {
        assertEquals(13193, run("input.txt"))
    }
}
