/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.joaogsma

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testExampleInputProblem1() {
        assertEquals(2, runProblem1("example.txt"))
    }

    @Test fun testRealInputProblem1() {
        assertEquals(599, runProblem1("input.txt"))
    }

    @Test fun testExampleInputProblem2() {
        assertEquals(4, runProblem2("example.txt"))
    }

    @Test fun testRealInputProblem2() {
        assertEquals(928, runProblem2("input.txt"))
    }
}
