/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.joaogsma

import kotlin.test.Test
import kotlin.test.assertEquals

class FoodCounterTest {
    @Test fun testExampleInputWindowSize1() {
        assertEquals(24000, run("example.txt", 1))
    }

    @Test fun testRealInputWindowSize1() {
        assertEquals(66186, run("input.txt", 1))
    }

    @Test fun testExampleInputWindowSize3() {
        assertEquals(45000, run("example.txt", 3))
    }

    @Test fun testRealInputWindowSize3() {
        assertEquals(196804, run("input.txt", 3))
    }
}
