/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.joaogsma

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testExampleInputVersion1() {
        assertEquals(95437, runProblem1("example.txt"))
    }

    @Test fun testRealInputVersion1() {
        assertEquals(1543140, runProblem1("input.txt"))
    }

    @Test fun testExampleInputVersion2() {
        assertEquals(24933642, runProblem2("example.txt"))
    }

    @Test fun testRealInputVersion2() {
        assertEquals(1117448, runProblem2("input.txt"))
    }
}
