/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.joaogsma

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testExampleInputVersion1() {
        assertEquals(13, runProblem1("example1.txt"))
    }

    @Test fun testRealInputVersion1() {
        assertEquals(6026, runProblem1("input.txt"))
    }

    @Test fun testExample1InputVersion2() {
        assertEquals(1, runProblem2("example1.txt"))
    }

    @Test fun testExample2InputVersion2() {
        assertEquals(36, runProblem2("example2.txt"))
    }

    @Test fun testRealInputVersion2() {
        assertEquals(2273, runProblem2("input.txt"))
    }
}
